---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  channel: {{ .Values.channel }}
  name: {{ .Values.operator }}
  source: {{ .Values.source }}
  sourceNamespace: {{ .Values.lifecycle_manager_namespace }}