apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespaces:
    - {{ .Release.Namespace }}
  upgradeStrategy:
    name: {{ .Values.upgrade_strategy }}