{{- with .Values.subscriptions }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
spec:
  channel: {{ .channel }}
  name: {{ .operator }}
  source: {{ .source }}
  sourceNamespace: {{ $.Values.lifecycle_manager_namespace }}
  startingCSV: {{ .starting_csv }}
  installPlanApproval: {{ .install_plan_approval }}
  {{ if .config }}
  config: {{ .config }}
  {{ end }}
{{- end }}